### PR TITLE
Adds sum basic summarizer

### PR DESCRIPTION
**Pull request by rmarronnier**
I realized doing this that I might have reimplemented (poorly ?) some of your `Cadmium::TfIdf` methods in my abstract summarization Class. 
I tried to understand (reading the code + specs) how to use the `Cadmium::TfIdf` Object  to get an `Hash(Term : String,  idf : Float64)` for the whole text input, but it seems it doesn't work like that.

### CODE REVIEW

**Comment by watzon** [comment]
As soon as I get a chance I'll download and test this. Thanks for your hard work!

**Comment by rmarronnier** [comment]
Great !

**Comment by rmarronnier** [comment]
No pressure here, but as soon as one summarizer is merged, I can start working on the next one :-) (I incrementally abstract out methods in the Summarizer class and improve the precedent algos as I add the next one)

**Comment by watzon** [comment]
Sorry I've had a lot of work to do this week. I'll check this out tomorrow and get things merged if I can.

**Comment by rmarronnier** [comment]
I get it totally. It can wait next week if you need to catch your breath :-)

**Comment by watzon** [comment]
Gonna go ahead and merge for now. I'll test performance and see what can be done in that area later. Thanks a lot for your hard work!

**Pull request merged**
